/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Lp2RouteImport } from './routes/lp2'
import { Route as LpRouteImport } from './routes/lp'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as CasamentoEmItapecericaDaSerraRouteImport } from './routes/casamento-em-itapecerica-da-serra'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSubmitLeadRouteImport } from './routes/api/public/submit-lead'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Lp2Route = Lp2RouteImport.update({
  id: '/lp2',
  path: '/lp2',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/lp2.lazy').then((d) => d.Route))
const LpRoute = LpRouteImport.update({
  id: '/lp',
  path: '/lp',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/lp.lazy').then((d) => d.Route))
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/download.lazy').then((d) => d.Route))
const CasamentoEmItapecericaDaSerraRoute =
  CasamentoEmItapecericaDaSerraRouteImport.update({
    id: '/casamento-em-itapecerica-da-serra',
    path: '/casamento-em-itapecerica-da-serra',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/casamento-em-itapecerica-da-serra.lazy').then(
      (d) => d.Route,
    ),
  )
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ApiPublicSubmitLeadRoute = ApiPublicSubmitLeadRouteImport.update({
  id: '/api/public/submit-lead',
  path: '/api/public/submit-lead',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/casamento-em-itapecerica-da-serra': typeof CasamentoEmItapecericaDaSerraRoute
  '/download': typeof DownloadRoute
  '/lp': typeof LpRoute
  '/lp2': typeof Lp2Route
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/submit-lead': typeof ApiPublicSubmitLeadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/casamento-em-itapecerica-da-serra': typeof CasamentoEmItapecericaDaSerraRoute
  '/download': typeof DownloadRoute
  '/lp': typeof LpRoute
  '/lp2': typeof Lp2Route
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/submit-lead': typeof ApiPublicSubmitLeadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/casamento-em-itapecerica-da-serra': typeof CasamentoEmItapecericaDaSerraRoute
  '/download': typeof DownloadRoute
  '/lp': typeof LpRoute
  '/lp2': typeof Lp2Route
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/submit-lead': typeof ApiPublicSubmitLeadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/casamento-em-itapecerica-da-serra'
    | '/download'
    | '/lp'
    | '/lp2'
    | '/sitemap.xml'
    | '/api/public/submit-lead'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/casamento-em-itapecerica-da-serra'
    | '/download'
    | '/lp'
    | '/lp2'
    | '/sitemap.xml'
    | '/api/public/submit-lead'
  id:
    | '__root__'
    | '/'
    | '/casamento-em-itapecerica-da-serra'
    | '/download'
    | '/lp'
    | '/lp2'
    | '/sitemap.xml'
    | '/api/public/submit-lead'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasamentoEmItapecericaDaSerraRoute: typeof CasamentoEmItapecericaDaSerraRoute
  DownloadRoute: typeof DownloadRoute
  LpRoute: typeof LpRoute
  Lp2Route: typeof Lp2Route
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicSubmitLeadRoute: typeof ApiPublicSubmitLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp2': {
      id: '/lp2'
      path: '/lp2'
      fullPath: '/lp2'
      preLoaderRoute: typeof Lp2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp': {
      id: '/lp'
      path: '/lp'
      fullPath: '/lp'
      preLoaderRoute: typeof LpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casamento-em-itapecerica-da-serra': {
      id: '/casamento-em-itapecerica-da-serra'
      path: '/casamento-em-itapecerica-da-serra'
      fullPath: '/casamento-em-itapecerica-da-serra'
      preLoaderRoute: typeof CasamentoEmItapecericaDaSerraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/submit-lead': {
      id: '/api/public/submit-lead'
      path: '/api/public/submit-lead'
      fullPath: '/api/public/submit-lead'
      preLoaderRoute: typeof ApiPublicSubmitLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasamentoEmItapecericaDaSerraRoute: CasamentoEmItapecericaDaSerraRoute,
  DownloadRoute: DownloadRoute,
  LpRoute: LpRoute,
  Lp2Route: Lp2Route,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicSubmitLeadRoute: ApiPublicSubmitLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
